//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webAreaMaster.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sistemaAreaMasterEntities : DbContext
    {
        public sistemaAreaMasterEntities()
            : base("name=sistemaAreaMasterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<barraData> barraData { get; set; }
        public virtual DbSet<depositoData> depositoData { get; set; }
        public virtual DbSet<familiaData> familiaData { get; set; }
        public virtual DbSet<PasswordResetTokens> PasswordResetTokens { get; set; }
        public virtual DbSet<productoData> productoData { get; set; }
        public virtual DbSet<sectorData> sectorData { get; set; }
        public virtual DbSet<stockBarrasData> stockBarrasData { get; set; }
        public virtual DbSet<stockDepositoData> stockDepositoData { get; set; }
        public virtual DbSet<usuarioData> usuarioData { get; set; }
        public virtual DbSet<usuarioRolData> usuarioRolData { get; set; }
    }
}
