//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webAreaMaster.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stockDepositoData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public stockDepositoData()
        {
            this.stockBarrasData = new HashSet<stockBarrasData>();
        }
    
        public int stockID { get; set; }
        public Nullable<int> stockDepositoID { get; set; }
        public Nullable<int> stockFamiliaID { get; set; }
        public Nullable<int> stockProductoID { get; set; }
        public Nullable<int> stockCodProducto { get; set; }
        public Nullable<decimal> stockPrecioVentaUnidad { get; set; }
        public Nullable<decimal> stockPrecioCostoUnidad { get; set; }
        public Nullable<decimal> stockPrecioCostoTotal { get; set; }
        public Nullable<decimal> stockCantidad { get; set; }
        public Nullable<System.DateTime> stockFechaIngreso { get; set; }
    
        public virtual depositoData depositoData { get; set; }
        public virtual familiaData familiaData { get; set; }
        public virtual productoData productoData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<stockBarrasData> stockBarrasData { get; set; }
    }
}
